#!/usr/bin/env bash
# shellcheck shell=sh # POSIX

set -e

# Change directory to the root of the repository
cd "$(dirname "$(realpath "$0")")/../.."

# Set SRC to the root of the repository
SRC="$PWD"

echo "SRC: $SRC"

TARGET_SH="$SRC/lib/library-functions.sh"

echo "Writing $TARGET_SH"

cat <<- AUTOGEN_INCLUDES_HEADER > "$TARGET_SH"
	###! Autogenerated file by $0 to source all of repository functions and provide shellcheck derivative

AUTOGEN_INCLUDES_HEADER

find "$SRC/lib/functions" -type f -name \*.sh | sort -h | while read -r path; do
	cat <<- AUTOGEN_INCLUDES_EACH >> "$TARGET_SH"
		# shellcheck source="./${path//$SRC\/lib\//}"
		. "\$SRC/${path//$SRC\//}"

	AUTOGEN_INCLUDES_EACH
done

# NOTE(Krey): Disabled, because it seems useless
# cat <<- AUTOGEN_INCLUDES_FOOTER >> "${TARGET_SH}"
# 	# no errors tolerated. one last time for the win!
# 	#set -o pipefail  # trace ERR through pipes - will be enabled "soon"
# 	#set -o nounset   ## set -u : exit the script if you try to use an uninitialised variable - one day will be enabled
# 	set -o errtrace # trace ERR through - enabled
# 	set -o errexit  ## set -e : exit the script if any statement returns a non-true return value - enabled
# 	# This file is/was autogenerated by ${0}; don't modify manually
# AUTOGEN_INCLUDES_FOOTER

echo "done."
